site_name: ç…§æ˜æœŸåˆŠ - ä¸€ç¯ç½‘
site_description: ä¸€ç¯ç…§æ˜æ‰‹å†Œï¼Œå­¦ä¹ ç…§æ˜çŸ¥è¯†æŠ€èƒ½ã€è§£å†³ç…§æ˜é—®é¢˜ï¼ŒæŸ¥è¯¢å„ç±»ç…§æ˜æ•°æ®
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  # - def_list
  # - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      # auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
theme:
  name: material
  language: zh
  logo: ./imgs/logo.png
  favicon: ./imgs/favicon.ico
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
plugins:
  - search:
      separator: '[\s\u200b\-]'
  # - git-revision-date-localized
repo_name: lightcax/wiki
repo_url: https://github.com/lightcax/wiki
nav:
  - ğŸŒˆé¦–é¡µ: 
    - ä»‹ç»: index.md
    - ä¸€ç¯ç½‘å¸®åŠ©: help.md
  - ğŸš€ç…§æ˜å‘¨åˆŠ:
    - ä»‹ç»: week/index.md
  - ğŸ’ç…§æ˜åŸºç¡€æ•™ç¨‹:
    - ç›®å½•: lightbasic/first.md
    - ç…§æ˜æ¦‚å¿µ: lightbasic/gn.md
    - å…‰å­¦çŸ¥è¯†: lightbasic/gx.md
    - å…‰æº: lightbasic/dgy.md
    - ç¯å…·: lightbasic/dj.md
    - å®‰å…¨æ€§èƒ½è¦æ±‚: lightbasic/annx.md
    - ç…§æ˜è®¾è®¡ä»‹ç»: lightbasic/zmsj.md
    - ç…§æ˜ç»„ç»‡æœºæ„: lightbasic/org.md
  - ğŸ—ƒï¸ç…§æ˜ç ”å‘æ‰‹å†Œ:
    - ç¯å…·è®¾è®¡å®‰è§„æ‰‹å†Œ: rd/dj.md
    - ledçƒæ³¡ç¯æŠ€æœ¯è§„èŒƒ: rd/bulb.md
    - ç…§æ˜è¡Œä¸šè½¯ä»¶æ±‡æ€»: rd/soft.md
    - ç…§æ˜è¡Œä¸šèµ„æ–™æ±‡æ€»: rd/pdf.md
  - ğŸ¯æ ‡å‡†ç±»æ‰‹å†Œ:
    - GB 7000ç¯å…·æ ‡å‡†: gb/gb7000.md
    - è¯»å†™æ€§èƒ½å°ç¯ä½œä¸šè¦æ±‚: gb/gb9473.md
  - ğŸ’¡å…¶ä»–ç…§æ˜æ‰‹å†Œ:
    - ç›®å½•: special/index.md
    - æ¤ç‰©ç…§æ˜æ‰‹å†Œ: special/plant.md
    - æ¿€å…‰ç…§æ˜: special/laser.md
  - ğŸ“ˆè¡Œä¸šæ•°æ®:
    - ç›®å½•: data/index.md
  - ğŸ”—ä¸€ç¯ç½‘: http://www.lightooo.com