site_name: ç…§æ˜å‘¨åˆŠ - ä¸€ç¯ç½‘
site_description: ä¸€ç¯ç…§æ˜æ‰‹å†Œï¼Œå­¦ä¹ ç…§æ˜çŸ¥è¯†æŠ€èƒ½ã€è§£å†³ç…§æ˜é—®é¢˜ï¼ŒæŸ¥è¯¢å„ç±»ç…§æ˜æ•°æ®
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  # - def_list
  # - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      # auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
theme:
  name: material
  language: zh
  logo: ./imgs/logo.png
  favicon: ./imgs/favicon.ico
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - accent: indigo
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-5
        name: åˆ‡æ¢æš—é»‘æ¨¡å¼
    - accent: black
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: åˆ‡æ¢ç™½å¤©æ¨¡å¼
plugins:
  - search:
      separator: '[\s\u200b\-]'
  # - git-revision-date-localized
repo_name: lightcax/wiki
repo_url: https://github.com/lightcax/wiki
nav:
  - ğŸŒˆé¦–é¡µ: 
    - ä»‹ç»: index.md
    - ä¸€ç¯ç½‘å¸®åŠ©: help.md
  - ğŸš€ç…§æ˜å‘¨åˆŠ:
    - ç¬¬1æœŸ: week/2022/1.md
  - ğŸ’ç…§æ˜åŸºç¡€æ•™ç¨‹:
    - ç›®å½•: lightbasic/first.md
    - ç…§æ˜æ¦‚å¿µ: lightbasic/gn.md
    - å…‰å­¦çŸ¥è¯†: lightbasic/gx.md
    - å…‰æº: lightbasic/dgy.md
    - ç¯å…·: lightbasic/dj.md
    - å®‰å…¨æ€§èƒ½è¦æ±‚: lightbasic/annx.md
    - ç…§æ˜è®¾è®¡ä»‹ç»: lightbasic/zmsj.md
    - ç…§æ˜ç»„ç»‡æœºæ„: lightbasic/org.md
  - ğŸ—ƒï¸ç…§æ˜ç ”å‘æ‰‹å†Œ:
    - ç¯å…·è®¾è®¡å®‰è§„æ‰‹å†Œ: rd/dj.md
    - ledçƒæ³¡ç¯æŠ€æœ¯è§„èŒƒ: rd/bulb.md
    - ç…§æ˜è¡Œä¸šè½¯ä»¶æ±‡æ€»: rd/soft.md
    - ç…§æ˜è¡Œä¸šèµ„æ–™æ±‡æ€»: rd/pdf.md
  - ğŸ¯æ ‡å‡†ç±»æ‰‹å†Œ:
    # - ç›®å½•: gb/index.md
    - GB 7000ç³»åˆ—ç¯å…·æ ‡å‡†: gb/gb7000.md
    - ç”µæ°”ç…§æ˜å’Œç±»ä¼¼è®¾å¤‡çš„æ— çº¿ç”µéªšæ‰°ç‰¹æ€§çš„é™å€¼å’Œæµ‹é‡æ–¹æ³•: gb/gbt17743.md
    - è¯»å†™æ€§èƒ½å°ç¯ä½œä¸šè¦æ±‚: gb/gb9473.md
    - å›½é™…ç…§æ˜æ ‡å‡†æ¸…å•: bz/globe.md
    - ä¸­å›½ç…§æ˜æ ‡å‡†æ¸…å•: gb/all.md
  - 7ï¸âƒ£GB 7000.1:
    - ç›®å½•: gb7000/index.md
    - æœ¯è¯­å’Œå®šä¹‰: gb7000/1.md
    - ç¯å…·çš„åˆ†ç±»: gb7000/2.md
    - æ ‡è®°: gb7000/3.md
    - ç»“æ„: gb7000/4.md
    - å¤–éƒ¨æ¥çº¿å’Œå†…éƒ¨æ¥çº¿: gb7000/5.md
    - æ¥åœ°è§„å®š: gb7000/7.md
    - é˜²è§¦ç”µä¿æŠ¤: gb7000/8.md
    - é˜²å°˜ ã€é˜²å›ºä½“å¼‚ç‰©å’Œé˜²æ°´: gb7000/9.md
    - ç»ç¼˜ç”µé˜»å’Œç”µæ°”å¼ºåº¦ã€æ¥è§¦ç”µæµå’Œä¿æŠ¤å¯¼ä½“ç”µæµ: gb7000/10.md
    - çˆ¬ç”µè·ç¦»å’Œç”µæ°”é—´éš™: gb7000/11.md
    - è€ä¹…æ€§è¯•éªŒå’Œçƒ­è¯•éªŒ: gb7000/12.md
    - è€çƒ­ã€è€ç«å’Œè€èµ·ç—•: gb7000/13.md
    - èºçº¹æ¥çº¿ç«¯å­: gb7000/14.md
    - æ— èºçº¹æ¥çº¿ç«¯å­å’Œç”µæ°”è¿æ¥ä»¶: gb7000/15.md
  - ğŸ’¡å…¶ä»–ç…§æ˜æ‰‹å†Œ:
    - ç›®å½•: special/index.md
    - æ¤ç‰©ç…§æ˜æ‰‹å†Œ: special/plant.md
    - æ¿€å…‰ç…§æ˜: special/laser.md
  - ğŸ“ˆè¡Œä¸šæ•°æ®:
    - ç›®å½•: data/index.md
  - ğŸ”—ä¸€ç¯ç½‘: http://www.lightooo.com